export default [
  'Thank someone for their generosity',
  'Ask someone what their favorite goal is',
  'Share food with someone',
  'Tell someone why you are excited for them',
  'Ask someone what they are most grateful for',
  "Praise someone's humor",
  'Make a card for someone',
  'Thank someone for their support',
  'Ask someone what their favorite memory is',
  'Share a book with someone',
  'Tell someone why you appreciate them',
  'Ask someone what they want to be remembered for',
  "Praise someone's ambition",
  'Make plans with friends',
  'Thank someone for their understanding',
  'Ask someone what their favorite gift is',
  'Share a game with someone',
  'Tell someone why you look up to them',
  'Ask someone what motivates them',
  "Praise someone's talent",
  'Make someone feel loved',
  'Thank someone for their contribution',
  'Ask someone what their favorite music is',
  'Share stories with someone',
  'Tell someone why you they are important to you',
  'Ask someone what they would change about themselves',
  "Praise someone's creativity",
  'Make a phone call to someone',
  'Thank someone for their positivity',
  'Ask someone what their favorite place is',
  'Share a walk with someone',
  'Tell someone why you support them',
  'Ask someone what they think the world needs',
  "Praise someone's courage",
  'Bake for someone',
  'Thank someone for their openness',
  'Ask someone what their favorite cause is',
  'Share a film with someone',
  'Tell someone why you are happy for them',
  'Ask someone what a perfect day would be for them',
  "Praise someone's love",
  'Write a letter to someone',
  'Thank someone for their thoughtfulness',
  'Ask someone what their favorite trait is',
  'Share hobbies with someone',
  'Tell someone why you care about them',
  'Ask someone what they would do if they could not fail',
  "Praise someone's perspective",
  'Make a picture for someone',
  'Thank someone for their respect',
  'Ask someone what their favorite food is',
  'Share music with someone',
  'Tell someone why you admire them',
  'Ask someone what they fear most',
  "Praise someone's strength",
  'Make a tradition with friends',
  'Thank someone for their service',
  'Ask someone what their favorite story is',
  'Play a game with someone',
  'Tell someone why you are proud of them',
  'Ask someone what they want to do before they die',
  "Praise someone's values",
  'Make time for someone',
  'Thank someone for their kindness',
  'Ask someone what their favorite project is',
  'Share a TED Talk with someone',
  'Tell someone why you cherish them',
  "Ask someone what's most important to them",
  "Praise someone's generosity",
  'Make a playlist for someone',
  'Thank someone for their humor',
  'Ask someone what their favorite book is',
  'Share a joke with someone',
  'Tell someone why you respect them',
  'Ask someone what their greatest accomplishment is',
  "Praise someone's understanding",
  'Make someone laugh',
  'Thank someone for their love',
  'Ask someone what their favorite experience is',
  'Share learnings with someone',
  'Tell someone why you are inspired by them',
  'Ask someone what makes them most happy',
  "Praise someone's skill",
  'Make a gift for someone',
  'Thank someone for their integrity',
  'Ask someone what their favorite film is',
  'Share a video with someone',
  'Tell someone why you love them',
  'Ask someone what makes them come alive',
  "Praise someone's wisdom",
  'Cook for someone'
];
