export default [
  'Play a game with someone',
  'Make a card for someone',
  'Make plans with someone',
  'Make a gift for someone',
  'Create art for someone',
  'Make someone laugh',
  'Smile at someone',
  'Cheer someone up',
  'Enjoy someone',
  'Share music with someone',
  'Share vulnerability with someone',
  'Share a book with someone',
  'Share a movie with someone',
  'Share a video with someone',
  'Share a TED Talk with someone',
  'Share food with someone',
  'Share a meal with someone',
  'Share a joke with someone',
  'Talk with someone',
  'Catch up with someone',
  'Have a conversation with someone',
  'Call someone',
  'Invite someone to dinner',
  'Walk with someone',
  'Watch a movie with someone',
  'Watch a video with someone',
  'Listen to music with someone',
  'Eat with someone',
  'Send someone a message',
  'Write someone a letter',
  'Forgive someone',
  'Apologize to someone',
  'Thank someone for their mentorship',
  'Thank someone for being a role model',
  'Thank someone for their leadership',
  'Thank someone for their respect',
  'Thank someone for their kindness',
  'Thank someone for your connection',
  'Thank someone for your relationship ',
  'Thank someone for their friendship',
  'Thank someone for their passion',
  'Thank someone for their inspiration',
  'Thank someone for their advice',
  'Thank someone for their encouragement',
  'Thank someone for their support',
  'Thank someone for their care',
  'Thank someone for their love',
  'Thank someone for their affirmation',
  'Thank someone for their respect',
  'Thank someone for their help',
  'Thank someone for their work',
  'Thank someone for their affection',
  'Thank someone for their understanding',
  'Thank someone for their generosity',
  'Thank someone for their humor',
  'Thank someone for their strength',
  'Thank someone for their positivity',
  'Thank someone for their openness',
  'Thank someone for their vulnerability',
  'Thank someone for their thoughtfulness',
  'Thank someone for their integrity',
  'Thank someone for their gratitude',
  'Give someone attention',
  'Give someone a gift',
  'Give someone a hug',
  'Give someone a high-five',
  'Give someone encouragement',
  'Give someone a compliment',
  'Give someone support',
  'Give someone a meal',
  'Bake for someone',
  'Cook for someone',
  'Be vulnerable with someone',
  'Joke around with someone',
  'Listen to someone',
  'Laugh with someone',
  'Help someone with their work',
  'Help someone with their project',
  'Help someone with their chores',
  'Learn more about someone',
  'Make a meal with someone',
  'Celebrate with someone',
  'Celebrate someone',
  "Celebrate someone's accomplishment",
  'Congratulate someone',
  'Congratulate someone for their achievement',
  'Tell someone why you are proud of them',
  'Tell someone why you love them',
  'Tell someone what you love about them',
  'Tell someone what you admire about them',
  'Tell someone why you admire them',
  'Tell someone why you respect them',
  'Tell someone why you appreciate them',
  'Tell someone why you are excited for them',
  'Tell someone why you look up to them',
  'Tell someone why they are important to you',
  'Tell someone why you are happy for them',
  'Tell someone why you cherish them',
  'Tell someone why you are inspired by them',
  "Praise someone's kindness",
  "Praise someone's respect",
  "Praise someone's strength",
  "Praise someone's strengths",
  "Praise someone's drive",
  "Praise someone's ambition",
  "Praise someone's talent",
  "Praise someone's grit",
  "Praise someone's skill",
  "Praise someone's values",
  "Praise someone's principles",
  "Praise someone's love",
  "Praise someone's humor",
  "Praise someone's courage",
  "Praise someone's generosity",
  "Praise someone's understanding",
  "Praise someone's gratitude"
];
